### ISSUE TITLE
where are the templates

### ISSUE THREAD

**Issue by mklingen** [personalrobotics/block_detector#1]
Looks like this repository is missing the template images used to search for the blocks. Where are they?

**Comment by psigen** [comment]
Are these omitted from the repo because they are large?  Maybe they are supposed to be stored in a companion zip or something.  Apriltags does the same thing to not have to store 4096 images in their repo.

**Comment by Shushman** [comment]
AaronW says they are in his local version of the code which he did not get around to committing. He'll send them over / direct me to them today.

**Comment by mklingen** [comment]
Okay cool. Can he also provide a brief readme describing how it works? I think I have the gist, but would like to know more.

**Comment by Shushman** [comment]
I'll find out specifics and put it up as a description.

**Comment by jeking04** [comment]
Here is some text from that email we were exhanging with Aaron yesterday. Maybe we can turn this into a readme:

Anyway, the way this thing works is by using very primitive template matching.  Somewhere, there's a blurry image of a block that I made with a light red top and a darker red bottom.  It basically compares windows in the observed image against this image and returns locations where it finds a close-ish match.  That close-ish is probably a matching threshold somewhere in the code.  To use blocks of a different color, you'd just need to make a new template and change the colors.  I seem to remember trying this before, but red worked the best (I think because it's so unlike the color of the table).  Given that this code was always a hack in the first place, I would HIGHLY recommend doing some testing to make sure it does what you need it to, and be ready to make changes/reinvent it where it fails.  Also, given that it uses direct color comparisons, I would be very careful about getting it to work in the lab, then trying to use it in a new location with possibly different lighting.  So maybe what I'm saying is, it would be wise to test under a number of lighting situations in the lab and make sure that it either works in all of them, or is easy enough to adjust thresholds or whatever on the spot when you are setting up for the demo.

**Comment by jeking04** [comment]
Also, I don't think Aaron has access to the lab anymore with the new gateway structure.  But I think I found the templates. Check out what is here:

/old_homes/awalsman/ros/local/pr-ros-pkg/trunk/perception_utils/block_detector/templates

I'm not sure where a good place to put these now is. Maybe in pr-ordata. I'll let you guys decide. @mkoval might also have some ideas.

**Comment by mklingen** [comment]
its a single tiny png file it seems. Makes much more sense just to put it in this repository.

**Comment by mklingen** [comment]
`remote: Permission to personalrobotics/block_detector.git denied to mklingen.`

**Comment by mklingen** [comment]
I pushed the templates. As you can see they're quite basic https://github.com/personalrobotics/block_detector/blob/master/templates/red_block.png . I will test this asap.

**Comment by jeking04** [comment]
whoops, okay I might have fixed it. try now.

On Wed, Sep 2, 2015 at 9:36 AM, mklingen <notifications@github.com> wrote:

> remote: Permission to personalrobotics/block_detector.git denied to
> mklingen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/personalrobotics/block_detector/issues/1#issuecomment-137162134>
> .
>



-- 
Jen King
